name: Build DULZ GUNUNG GEDE APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.5.1

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Check Godot
        run: |
          godot --version

      - name: Import Project
        run: |
          godot --headless --editor --quit --path .

      - name: Build APK
        run: |
          mkdir -p build
          godot \
            --headless \
            --path . \
            --export-debug "Android" \
            build/DulzGunungGede-debug.apk

      - name: Check APK
        run: |
          ls -lh build/
          du -h build/DulzGunungGede-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DULZ-GUNUNG-GEDE-APK
          path: build/DulzGunungGede-debug.apk
          if-no-files-found: error
